# Managed by GateRank log maintenance
@@LOG_DIR@@/access.log @@LOG_DIR@@/error.log {
    size 100M
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    su root root
}
