import assert from 'node:assert/strict';
import test from 'node:test';
import { buildRankings } from '../src/services/rankingService';

test('buildRankings excludes normal and down airports from risk ranking', () => {
  const rankings = buildRankings('2026-03-24', [
    {
      airport: {
        id: 1,
        name: 'Normal Airport',
        website: 'https://normal.example.com',
        status: 'normal',
        is_listed: true,
        plan_price_month: 10,
        has_trial: true,
        tags: [],
        created_at: '2025-01-01',
      },
      metrics: {
        airport_id: 1,
        date: '2026-03-24',
        uptime_percent_30d: 90,
        median_latency_ms: 60,
        median_download_mbps: 100,
        packet_loss_percent: 0,
        stable_days_streak: 10,
        domain_ok: false,
        ssl_days_left: 3,
        recent_complaints_count: 8,
        history_incidents: 2,
      },
      score: {
        s: 70,
        p: 70,
        c: 70,
        r: 40,
        risk_penalty: 60,
        score: 60,
        recent_score: 60,
        historical_score: 60,
        final_score: 60,
        details: {},
      },
    },
    {
      airport: {
        id: 2,
        name: 'Risk Airport',
        website: 'https://risk.example.com',
        status: 'risk',
        is_listed: true,
        plan_price_month: 10,
        has_trial: true,
        tags: [],
        created_at: '2025-01-01',
      },
      metrics: {
        airport_id: 2,
        date: '2026-03-24',
        uptime_percent_30d: 80,
        median_latency_ms: 80,
        median_download_mbps: 50,
        packet_loss_percent: 5,
        stable_days_streak: 1,
        domain_ok: false,
        ssl_days_left: 1,
        recent_complaints_count: 10,
        history_incidents: 3,
      },
      score: {
        s: 50,
        p: 40,
        c: 45,
        r: 20,
        risk_penalty: 80,
        score: 35,
        recent_score: 35,
        historical_score: 35,
        final_score: 35,
        details: {},
      },
    },
    {
      airport: {
        id: 3,
        name: 'Down Airport',
        website: 'https://down.example.com',
        status: 'down',
        is_listed: true,
        plan_price_month: 10,
        has_trial: false,
        tags: ['不推荐'],
        created_at: '2025-01-01',
      },
      metrics: {
        airport_id: 3,
        date: '2026-03-24',
        uptime_percent_30d: 20,
        median_latency_ms: 999,
        median_download_mbps: 0,
        packet_loss_percent: 100,
        stable_days_streak: 0,
        domain_ok: false,
        ssl_days_left: null,
        recent_complaints_count: 12,
        history_incidents: 5,
      },
      score: {
        s: 0,
        p: 0,
        c: 0,
        r: 0,
        risk_penalty: 100,
        score: 0,
        recent_score: 0,
        historical_score: 0,
        final_score: 0,
        details: {},
      },
    },
  ]);

  assert.deepEqual(rankings.risk.map((item) => item.airport_id), [2]);
  assert.ok(rankings.today.every((item) => item.airport_id !== 3));
  assert.ok(rankings.stable.every((item) => item.airport_id !== 3));
});
